### PR TITLE
Feature/proc refactor

### PR DESCRIPTION
**Pull request by CEgerer93**
Refactor code to allow for user-defined experiments, shorthand abbreviations, and concatenated time windows.

To-Do:
- [x] modify CMakeLists.txt to move *Proc/*Plot scripts to build directory.
- [x] in building, make *Plot scripts directly callable.

### CODE REVIEW

**Comment by rtodling** [comment]
The other comment I will make is that it seems that grdstats.py cannot figure out on its own where to find gritas.x ... in order words it requires the user to place the path of gritas in the PATH ... perhaps this can be changed to do something like, if gritas,x is not in the path look for it in the same location as grdstats.py is ...

**Comment by CEgerer93** [comment]
> The other comment I will make is that it seems that grdstats.py cannot figure out on its own where to find gritas.x ... in order words it requires the user to place the path of gritas in the PATH ... perhaps this can be changed to do something like, if gritas,x is not in the path look for it in the same location as grdstats.py is ...

Path to `gritas.x` is now set via CMakeLists.txt by substituting for `CMAKE_INSTALL_PREFIX` in `grit_util.py.in` - see [here](https://github.com/GEOS-ESM/GrITAS/blob/600357b42be246a764c2f3ac62db6cbea22ff334/src/Applications/GrITAS_Proc/grit_util.py.in#L226).

**Comment by CEgerer93** [comment]
When comparing two experiments, confidence intervals are now shown as filled regions rather than individual errors bars. See [here](https://github.com/GEOS-ESM/GrITAS/blob/b6d384ce9159f0760cf4f8c872c07c670b930ba2/src/Applications/GrITAS_Plot/figutil.py#L340).

**Review by rtodling — APPROVED** [review]
I exercised these - w/ your help - and was able to follow he readme's as well. These seem pretty good.

**Pull request merged**
