### PR TITLE
Addresses issue #5

### PR DESCRIPTION
**Pull request by CEgerer93**
Some functions now have slightly changed functionality. I will modify the relevant docstrings and READMEs, as appropriate.

### CODE REVIEW

**Comment by rtodling** [comment]
Odd I am getting an error when I specify the key for ratio+difference

**iniPlotYaml.py -d 20230801/20230831 -e X0049/X0046D --compVia=difference+ratio --resid --C --M**
Traceback (most recent call last):
  File "/gpfsm/dnb05/projects/p139/rtodling/TEST/GrTest/../GrITAS/install/bin/iniPlotYaml.py", line 100, in <module>
    plotParams = PlotParams(regions=[r.name for r in regions],timeSeries=options.T,timeSeriesVar=options.tSeriesVar,
  File "/gpfsm/dnb05/projects/p139/rtodling/TEST/GrITAS/install/bin/plot_util.py", line 568, in __init__
    self.__valid__()
  File "/gpfsm/dnb05/projects/p139/rtodling/TEST/GrITAS/install/bin/plot_util.py", line 583, in __valid__
    raise ValueError("%s is an unsupported manner to compare two experiments - please select from %s"%
ValueError: difference+ratio is an unsupported manner to compare two experiments - please select from ['ratio', 'difference']

**Comment by CEgerer93** [comment]
Are you sure you are on the `feature/plot-refinements` branch and did a fresh pull?
The `PlotParams` class in `plot_util.py` checks for valid `compareVia` types.

I can see on the `main` branch [here](https://github.com/GEOS-ESM/GrITAS/blob/a24a2d47b5772e670fa365088900d277b31a3b94/src/Applications/GrITAS_Plot/plot_util.py#L582) that only 'ratio' and 'difference' are supported. On the `feature/plot-refinements` branch [here](https://github.com/GEOS-ESM/GrITAS/blob/b677346064e5030aada143ba08636ea3654806b8/src/Applications/GrITAS_Plot/plot_util.py#L582), 'difference+ratio' and 'ratio+difference' are now also supported.

**Comment by rtodling** [comment]
I just checked the whole things out fresh to make sure nothing is odd on my end; rebuild; and still have the same error!

**Comment by CEgerer93** [comment]
I've confirmed I have locally the same changes in `feature/plot-refinements` as here on GitHub. I run:
`iniPlotYaml.py -d 20230801/20230831 -e X0049/X0046D --compVia=difference+ratio --resid --C --M`
(as above) and there is no error.

Another reason why I'm suspecting your binaries don't reflect the recent changes is the experiment names are all capitalized in your example. Per a suggestion, I removed the use of `.upper()` in `build-yaml.py` in commit https://github.com/GEOS-ESM/GrITAS/commit/600357b42be246a764c2f3ac62db6cbea22ff334. So, unless the user capitalizes experiment names, the names should not be capitalized.

Let's have a conversation to sort this one out.

**Comment by rtodling** [comment]
> I've confirmed I have locally the same changes in `feature/plot-refinements` as here on GitHub. I run: `iniPlotYaml.py -d 20230801/20230831 -e X0049/X0046D --compVia=difference+ratio --resid --C --M` (as above) and there is no error.
> 
> Another reason why I'm suspecting your binaries don't reflect the recent changes is the experiment names are all capitalized in your example. Per a suggestion, I removed the use of `.upper()` in `build-yaml.py` in commit [600357b](https://github.com/GEOS-ESM/GrITAS/commit/600357b42be246a764c2f3ac62db6cbea22ff334). So, unless the user capitalizes experiment names, the names should not be capitalized.
> 
> Let's have a conversation to sort this one out.

Hi Colin - Happy New Year!

I might have done something wrong. It now seems to work - that is, it produces a plot. However,  I only see one of the curves come out (the mean) - there seems to be an issue w/ the x-limits for the standard deviation; as a consequence, the standard deviation does not show up. I think we need to have something that maps the number of "measures" to the number of min/max values set within instruments category  ... something like:

instruments: 
   atmsnpp:
      vertical units:
         difference: 
            min value: ...
            max value: ...
         ratio: 
            min value: ...
            max value: ...


or 

instruments: 
   atmsnpp:
      vertical units:
         mean: 
            min value: ...
            max value: ...
         standard deviation: 
            min value: ...
            max value: ...

**Comment by rtodling** [comment]
Also, one more thing I noticed ... I think the plot for the ratio is showing <ctl> / < exp> instead of the other way around ... can you double check that, please?

**Comment by CEgerer93** [comment]
> Also, one more thing I noticed ... I think the plot for the ratio is showing / < exp> instead of the other way around ... can you double check that, please?

I had the figure labels of 'EXP' and 'CTL' switched, while the plot itself is correct. I've corrected the labeling.

**Comment by CEgerer93** [comment]
When working with both ratios and differences of two experiments, perhaps it would be easier to work out internally what the domain for each should be? Right now, the domain for the difference in two experiment sample means is computed internally - the domain is symmetric about zero with a half-width of 105% of max( abs(difference min), abs(difference max) ) 

```python
ax.set_xlim([-1.05*max(np.abs([ax2_min,ax2_max])),1.05*max(np.abs([ax2_min,ax2_max]))])
```

Something similar could be done for the ratios, and then `min value` and `max value` for each instrument and statistic could be dropped. This would prevent proliferation.

**Comment by rtodling** [comment]
> When working with both ratios and differences of two experiments, perhaps it would be easier to work out internally what the domain for each should be? Right now, the domain for the difference in two experiment sample means is computed internally - the domain is symmetric about zero with a half-width of 105% of max( abs(difference min), abs(difference max) )
> 
> ```python
> ax.set_xlim([-1.05*max(np.abs([ax2_min,ax2_max])),1.05*max(np.abs([ax2_min,ax2_max]))])
> ```
> 
> Something similar could be done for the ratios, and then `min value` and `max value` for each instrument and statistic could be dropped. This would prevent proliferation.

The problem with that is when we have three exps - a CTL, EXP1, EXP2 ... and run plot EXP1/CTL and EXP2/CTL - in different plots because the runs were ran at different times ... the x-axis scales can come up looking different and it will make it hard to compare the ratios against each other.

**Comment by rtodling** [comment]
> > Also, one more thing I noticed ... I think the plot for the ratio is showing / < exp> instead of the other way around ... can you double check that, please?
> 
> I had the figure labels of 'EXP' and 'CTL' switched, while the plot itself is correct. I've corrected the labeling.

I think the issue w/ the curves coming out in opposite order for me are related to the use (and description in the README.md) of the iniPlotYaml.py when two experiments are passed as options with names split between a "/". Perhaps we need to clarify in the instruments that the order matters ... and CTL/EXP as opposed to what I did which was EXP/CTL in the command line.

**Comment by CEgerer93** [comment]
> > When working with both ratios and differences of two experiments, perhaps it would be easier to work out internally what the domain for each should be? Right now, the domain for the difference in two experiment sample means is computed internally - the domain is symmetric about zero with a half-width of 105% of max( abs(difference min), abs(difference max) )
> > ```python
> > ax.set_xlim([-1.05*max(np.abs([ax2_min,ax2_max])),1.05*max(np.abs([ax2_min,ax2_max]))])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Something similar could be done for the ratios, and then `min value` and `max value` for each instrument and statistic could be dropped. This would prevent proliferation.
> 
> The problem with that is when we have three exps - a CTL, EXP1, EXP2 ... and run plot EXP1/CTL and EXP2/CTL - in different plots because the runs were ran at different times ... the x-axis scales can come up looking different and it will make it hard to compare the ratios against each other.

Indeed, that's true. I overlooked that possibility. I'll leave out any automatic selection of the domain.

**Review by rtodling — APPROVED** [review]
Seems good. Thank you.

**Pull request merged**
