### PR TITLE
Feature/gritas plot

### PR DESCRIPTION
**Pull request by CEgerer93**
Support for visualizing statistics per observer level or across a time series for one and two experiments; comparisons made between statistics when two experiments are considered.

To-Do:
- [ ] This PR incorporates yamls for residuals only. Need to include observation impact and DFS.
- [ ] Settle on degrees of freedom when computing t-scores and left/right chi-square scores when assigning confidence intervals to sample means, standard deviations, etc.

### CODE REVIEW

**Comment by CEgerer93** [comment]
The conflicts with `GrITAS_Proc` are due to the `GrITAS_Proc` directory having been removed from the
`feature/gritas-plot` branch. The contents of `GrITAS_Proc` brought into `main` via #2 should be kept
alongside this PR #3.

**Review by rtodling — DISMISSED** [review]

**Comment by rtodling** [comment]
There seems to be some conflict that needs resolution ... can you take care of it Colin? Thanks

**Review by CEgerer93 — COMMENTED** [review]
Changes do not affect the main branch. Conflicts in merging stemming from `GrITAS_Proc` directory being removed from `feature/gritas_plot`, and `GrITAS_Plot` directory having been removed from `feature/gritas_proc` and, based on #2, the `main` branch.

**Comment by CEgerer93** [comment]
> There seems to be some conflict that needs resolution ... can you take care of it Colin? Thanks

Mistakenly deleted entirety of src/Applications/GrITAS_Proc directory from `feature/gritas-plot` feature branch. This was causing merge conflict into `main`.

Checked out the missing directory from `main` and applied it onto `feature/gritas-plot`. Merging proceeded seamlessly locally.

**Comment by CEgerer93** [comment]
Made some updates to README and functionality driving the plotting. Hopefully making things simpler for the user, and less susceptible to edge cases.

**Comment by CEgerer93** [comment]
Completed docstrings and added minor tweaks. This is ready to go. Do you have further suggestions or comments? Can this be merged?

**Comment by CEgerer93** [comment]
@rtodling, Do you have any further suggestions or revisions?

**Review by rtodling — APPROVED** [review]
Hi Colin, I am approving the here ... but it would be nice if we could sit down tomorrow and you could run me trough this and help set up things on my end so I can run the tool the same way you set it here ... once I have that, it will be easier for me to make more sound comments. Thx

**Pull request merged**
